const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),N=10,HALF=N/2;
const faces=[{n:[0,0,1],r:[1,0,0],d:[0,1,0]},{n:[1,0,0],r:[0,0,-1],d:[0,1,0]},{n:[0,0,-1],r:[-1,0,0],d:[0,1,0]},{n:[-1,0,0],r:[0,0,1],d:[0,1,0]},{n:[0,-1,0],r:[1,0,0],d:[0,0,1]},{n:[0,1,0],r:[1,0,0],d:[0,0,-1]}],dirs=[[0,-1],[1,0],[0,1],[-1,0]];
let snake=[],apples=[],dir=1,nextDir=1,inputQueue=[],score=0,running=false,paused=false,player='',last=0,stepMs=185,yaw=.18,pitch=-.16,targetYaw=.18,targetPitch=-.16;
const $=s=>document.querySelector(s),dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2],add=(a,b,s=1)=>[a[0]+b[0]*s,a[1]+b[1]*s,a[2]+b[2]*s],eq=(a,b)=>a[0]===b[0]&&a[1]===b[1]&&a[2]===b[2],keyOf=p=>`${p.f}:${p.x}:${p.y}`;
const pauseBtn=$('#pause');
const homeBtn=$('#goHome');
const SCORE_RESET_VERSION='snake-scores-reset-2026-07-17';
if(localStorage.getItem('cube-serpent-score-reset')!==SCORE_RESET_VERSION){localStorage.removeItem('cube-serpent-scores');localStorage.setItem('cube-serpent-score-reset',SCORE_RESET_VERSION)}
const directionVectors={up:[0,-1],right:[1,0],down:[0,1],left:[-1,0]};
function queueDirection(wanted){if(running&&snake.length&&!paused&&inputQueue.length<4)inputQueue.push(wanted)}
function cellCenter(p,lift=.03){const f=faces[p.f];let q=f.n.map(v=>v*(HALF+lift));q=add(q,f.r,p.x-HALF+.5);return add(q,f.d,p.y-HALF+.5)}
function move(p,heading){const[dx,dy]=dirs[heading];let x=p.x+dx,y=p.y+dy;if(x>=0&&x<N&&y>=0&&y<N)return{f:p.f,x,y};const old=faces[p.f],worldDir=dx?old.r.map(v=>v*dx):old.d.map(v=>v*dy),nf=faces.findIndex(f=>eq(f.n,worldDir)),neo=faces[nf],newWorld=old.n.map(v=>-v),center=cellCenter(p,0);x=Math.max(0,Math.min(N-1,Math.floor(dot(center,neo.r)+HALF)));y=Math.max(0,Math.min(N-1,Math.floor(dot(center,neo.d)+HALF)));let nd;if(eq(newWorld,neo.r)){nd=1;x=0}else if(eq(newWorld,neo.r.map(v=>-v))){nd=3;x=N-1}else if(eq(newWorld,neo.d)){nd=2;y=0}else{nd=0;y=N-1}return{f:nf,x,y,heading:nd}}
function spawnApple(){const used=new Set([...snake,...apples].map(keyOf));let p;do p={f:Math.floor(Math.random()*6),x:Math.floor(Math.random()*N),y:Math.floor(Math.random()*N)};while(used.has(keyOf(p)));return p}
function reset(){snake=[{f:0,x:5,y:5},{f:0,x:4,y:5},{f:0,x:3,y:5}];apples=[];dir=1;nextDir=1;inputQueue=[];score=0;stepMs=185;running=true;paused=false;yaw=.18;pitch=-.16;targetYaw=.18;targetPitch=-.16;while(apples.length<3)apples.push(spawnApple());updateHud();$('#message').classList.add('hidden');$('#status').textContent='RUN ACTIVE';if(pauseBtn)pauseBtn.textContent='PAUSE';last=performance.now()}
function tick(){while(inputQueue.length){const nd=screenDirection(snake[0].f,inputQueue.shift());if((nd+2)%4!==dir){nextDir=nd;break}}dir=nextDir;const previousHead=snake[0],head=move(previousHead,dir);if(snake.some(p=>keyOf(p)===keyOf(head))){gameOver();return}if(head.f!==previousHead.f)followFace(head.f);if(head.heading!==undefined){dir=head.heading;nextDir=dir}snake.unshift(head);const ai=apples.findIndex(a=>keyOf(a)===keyOf(head));if(ai>=0){score+=10;stepMs=Math.max(85,185-score*.8);apples.splice(ai,1);apples.push(spawnApple());updateHud()}else snake.pop()}
function records(){let saved;try{saved=JSON.parse(localStorage.getItem('cube-serpent-scores'))||[]}catch{saved=[]}const bestByPlayer=new Map();for(const entry of Array.isArray(saved)?saved:[]){const name=String(entry.name||'PILOT').trim().slice(0,16)||'PILOT',entryScore=Math.max(0,Number(entry.score)||0),key=name.toLowerCase(),current=bestByPlayer.get(key);if(!current||entryScore>current.score)bestByPlayer.set(key,{name,score:entryScore,date:entry.date||''})}return[...bestByPlayer.values()]}function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function saveScore(){const list=records(),key=player.toLowerCase(),existing=list.findIndex(r=>r.name.toLowerCase()===key),run={name:player,score,date:new Date().toLocaleDateString()};if(existing<0)list.push(run);else if(score>list[existing].score)list[existing]=run;localStorage.setItem('cube-serpent-scores',JSON.stringify(list));renderScores();updateHud()}function renderScores(){const list=records().sort((a,b)=>b.score-a.score);$('#scores').innerHTML=list.slice(0,12).map(r=>`<li><span>${escapeHtml(r.name)}<small>${r.date}</small></span><b>${String(r.score).padStart(3,'0')}</b></li>`).join('');$('#empty-scores').style.display=list.length?'none':'block'}function updateHud(){$('#score').textContent=String(score).padStart(3,'0');const best=Math.max(0,...records().filter(r=>r.name.toLowerCase()===player.toLowerCase()).map(r=>r.score),score);$('#best').textContent=String(best).padStart(3,'0')}function gameOver(){running=false;paused=false;saveScore();$('#message-title').textContent='RUN ENDED';$('#message-copy').textContent=`${player}, you crossed ${Math.floor(score/10)} cube sectors and scored ${score} points.`;$('#message').classList.remove('hidden');$('#status').textContent='COLLISION DETECTED';if(pauseBtn)pauseBtn.textContent='PAUSE'}function togglePause(){if(!running)return;paused=!paused;$('#status').textContent=paused?'PAUSED':'RUN ACTIVE';if(pauseBtn)pauseBtn.textContent=paused?'RESUME':'PAUSE';if(!paused)last=performance.now()}
function rotate(p){let[x,y,z]=p,cy=Math.cos(yaw),sy=Math.sin(yaw);[x,z]=[x*cy+z*sy,-x*sy+z*cy];let cp=Math.cos(pitch),sp=Math.sin(pitch);[y,z]=[y*cp-z*sp,y*sp+z*cp];return[x,y,z]}function project(p){const[x,y,z]=rotate(p),scale=Math.min(canvas.width,canvas.height)*.054,persp=14/(14-z);return{x:canvas.width/2+x*scale*persp,y:canvas.height/2+y*scale*persp,z,scale:persp}}
function screenDirection(face,wanted){const f=faces[face],center=cellCenter(snake[0],.15),origin=project(center),candidates=dirs.map(([dx,dy],heading)=>{const world=dx?f.r.map(v=>v*dx):f.d.map(v=>v*dy),point=project(add(center,world,.7)),vx=point.x-origin.x,vy=point.y-origin.y,len=Math.hypot(vx,vy)||1;return{heading,score:(vx*wanted[0]+vy*wanted[1])/len}});return candidates.sort((a,b)=>b.score-a.score)[0].heading}
function nearestAngle(angle,reference){return angle+Math.round((reference-angle)/(Math.PI*2))*Math.PI*2}function followFace(face){if(face===4||face===5){targetPitch=nearestAngle(face===4?-Math.PI/2:Math.PI/2,targetPitch);return}const baseYaw=[0,-Math.PI/2,Math.PI,Math.PI/2][face],normal={yaw:nearestAngle(baseYaw,targetYaw),pitch:nearestAngle(0,targetPitch)},overEdge={yaw:nearestAngle(baseYaw+Math.PI,targetYaw),pitch:nearestAngle(Math.PI,targetPitch)},normalDistance=(normal.yaw-targetYaw)**2+(normal.pitch-targetPitch)**2,edgeDistance=(overEdge.yaw-targetYaw)**2+(overEdge.pitch-targetPitch)**2,{yaw:nextYaw,pitch:nextPitch}=normalDistance<=edgeDistance?normal:overEdge;targetYaw=nextYaw;targetPitch=nextPitch}function angleStep(current,target,amount){let delta=(target-current+Math.PI)%(Math.PI*2)-Math.PI;if(delta<-Math.PI)delta+=Math.PI*2;return current+delta*amount}
function quad(face,x,y,lift=0){const f=faces[face],gap=.045,a=x-HALF+gap,b=x-HALF+1-gap,c=y-HALF+gap,d=y-HALF+1-gap,n=HALF+lift,point=(rr,dd)=>add(add(f.n.map(v=>v*n),f.r,rr),f.d,dd);return[point(a,c),point(b,c),point(b,d),point(a,d)]}function facePlane(face,lift=0){const f=faces[face],n=HALF+lift,point=(rr,dd)=>add(add(f.n.map(v=>v*n),f.r,rr),f.d,dd);return[point(-HALF,-HALF),point(HALF,-HALF),point(HALF,HALF),point(-HALF,HALF)]}function polygon(points,fill,stroke,alpha=1){const ps=points.map(project);ctx.globalAlpha=alpha;ctx.beginPath();ctx.moveTo(ps[0].x,ps[0].y);ps.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke()}ctx.globalAlpha=1}
function drawAppleIndicator(apple){const rotated=rotate(cellCenter(apple,.3)),cx=canvas.width/2,cy=canvas.height/2;let vx=rotated[0],vy=rotated[1],len=Math.hypot(vx,vy);if(len<.1){vx=0;vy=-1;len=1}vx/=len;vy/=len;const radius=Math.min(canvas.width,canvas.height)*.39,x=cx+vx*radius,y=cy+vy*radius,size=Math.max(9,Math.min(canvas.width,canvas.height)*.012);ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(vy,vx));ctx.shadowColor='#ff3939';ctx.shadowBlur=16;ctx.fillStyle='#ff554b';ctx.beginPath();ctx.moveTo(size,0);ctx.lineTo(-size*.55,-size*.7);ctx.lineTo(-size*.55,size*.7);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#ffd0c7';ctx.lineWidth=2;ctx.stroke();ctx.restore()}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);yaw=angleStep(yaw,targetYaw,.24);pitch=angleStep(pitch,targetPitch,.24);const visible=faces.map(f=>rotate(f.n)[2]>-.03);if(snake.length)visible[snake[0].f]=true;const faceColors=['#25382a','#20342b','#29352b','#24372f','#2b3927','#203832'],planes=[];for(let f=0;f<6;f++)if(visible[f]){const q=facePlane(f);planes.push({f,q,z:q.reduce((s,p)=>s+rotate(p)[2],0)/4})}planes.sort((a,b)=>a.z-b.z).forEach(p=>polygon(p.q,'#17251c','#69806e',1));const cells=[];for(let f=0;f<6;f++)if(visible[f])for(let y=0;y<N;y++)for(let x=0;x<N;x++){const q=quad(f,x,y,.015);cells.push({z:q.reduce((s,p)=>s+rotate(p)[2],0)/4,q,f,x,y})}cells.sort((a,b)=>a.z-b.z);cells.forEach(c=>polygon(c.q,(c.x+c.y)%2?faceColors[c.f]:'#2d4132','#4a6250',1));const items=[];snake.forEach((p,i)=>{if(!visible[p.f])return;const q=quad(p.f,p.x,p.y,.08+(i===0?.03:0));items.push({z:rotate(cellCenter(p,.1))[2],q,type:i===0?'head':'snake',p})});apples.forEach(p=>{if(visible[p.f])items.push({z:rotate(cellCenter(p,.2))[2],p,type:'apple'})});items.sort((a,b)=>a.z-b.z);items.forEach(o=>{if(o.type==='snake'||o.type==='head'){polygon(o.q,o.type==='head'?'#d5ff70':'#9ee830',o.type==='head'?'#f5ffd8':'#c8ff64');if(o.type==='head'){const c=project(cellCenter(o.p,.13));ctx.fillStyle='#111';ctx.beginPath();ctx.arc(c.x,c.y,3.2*c.scale,0,Math.PI*2);ctx.fill()}}else{const c=project(cellCenter(o.p,.3)),r=8*c.scale;ctx.shadowColor='#ff3434';ctx.shadowBlur=18;ctx.fillStyle='#ff4d42';ctx.beginPath();ctx.arc(c.x,c.y,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#ffd1a0';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(c.x,c.y-r);ctx.lineTo(c.x+3,c.y-r-6);ctx.stroke()}});apples.filter(a=>!visible[a.f]).forEach(drawAppleIndicator)}
function frame(t){if(running&&!paused&&t-last>stepMs){tick();last=t}draw();requestAnimationFrame(frame)}function resize(){const rect=canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1);canvas.width=rect.width*dpr;canvas.height=rect.height*dpr}
window.addEventListener('resize',resize);window.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!paused)togglePause()});window.addEventListener('keydown',e=>{const wanted={ArrowUp:directionVectors.up,ArrowRight:directionVectors.right,ArrowDown:directionVectors.down,ArrowLeft:directionVectors.left};if(e.key==='Escape'&&running){e.preventDefault();togglePause();return}if(e.key in wanted&&running&&snake.length&&!paused){e.preventDefault();if(!e.repeat)queueDirection(wanted[e.key])}});document.querySelectorAll('[data-snake-dir]').forEach(button=>button.addEventListener('click',()=>queueDirection(directionVectors[button.dataset.snakeDir])));let swipeStart=null;canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;swipeStart={x:e.clientX,y:e.clientY,id:e.pointerId};canvas.classList.add('dragging');if(canvas.setPointerCapture)canvas.setPointerCapture(e.pointerId);e.preventDefault()});canvas.addEventListener('pointerup',e=>{if(!swipeStart||e.pointerId!==swipeStart.id)return;const dx=e.clientX-swipeStart.x,dy=e.clientY-swipeStart.y;swipeStart=null;canvas.classList.remove('dragging');if(Math.max(Math.abs(dx),Math.abs(dy))<24)return;queueDirection(Math.abs(dx)>Math.abs(dy)?(dx>0?directionVectors.right:directionVectors.left):(dy>0?directionVectors.down:directionVectors.up));e.preventDefault()});canvas.addEventListener('pointercancel',()=>{swipeStart=null;canvas.classList.remove('dragging')});if(pauseBtn)pauseBtn.addEventListener('click',togglePause);if(homeBtn)homeBtn.addEventListener('click',()=>{window.location.href='index.html'});$('#login-form').addEventListener('submit',e=>{e.preventDefault();player=$('#username').value.trim().slice(0,16)||'PILOT';$('#player').textContent=player.toUpperCase();$('#login').classList.add('hidden');reset()});$('#restart').addEventListener('click',()=>{running=false;paused=false;$('#message').classList.add('hidden');$('#login').classList.remove('hidden');$('#username').value=player;$('#username').focus();$('#username').select();$('#status').textContent='AWAITING PILOT';if(pauseBtn)pauseBtn.textContent='PAUSE'});resize();renderScores();requestAnimationFrame(frame);
if(window.PP)PP.startCoinTimer({rate:1,isActive:()=>running&&!paused});
